POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "user"
}

###

GET http://localhost:4000/data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidXNlciIsImlhdCI6MTYyMTcxMDY0MCwiZXhwIjoxNjIxNzEwNzAwfQ.wUIYEjdeAqKvfJ1kTyfxutejl6Vs4-mXgTcToP2s38k

###

POST http://localhost:5000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidXNlciIsImlhdCI6MTYyMTcxMDU3NX0.s__rtytII2fA6jVXhm_Zvr_v9kXSlrhDvbB8RByUsPc"
}